name: FirstPlugIn
main: io.github.Tuor.Plugin
version: 1.0
commands:
   kill1:
      description: Kills the player who typed this command
      usage: /<command> [player]
   getPlayerList:
      description: Gets a player list
      usage: /<command> [player]